name: Django Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and run tests (if backend exists)
        run: |
          if [ -f "backend/requirements.txt" ]; then
            pip install -r backend/requirements.txt
            python manage.py test || exit 1
          else
            echo "No backend found. Skipping Django tests."
          fi
        env:
          DJANGO_SETTINGS_MODULE: backend.settings  # cámbialo por el nombre real del módulo
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }} 
